version: '2'
services:
    logbook-app:
        image: logbook
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://logbook-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=logbook
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    logbook-mongodb:
        extends:
            file: mongodb.yml
            service: logbook-mongodb
